name: "CLI deploy"

on:
  workflow_dispatch:
    inputs:
      projectName:
        description: "KindFi"
        required: true
        type: string
jobs:
  deploy:
    name: CLI Deploy
    runs-on: ubuntu-latest
    environment:
      name: DEPLOYMENT
    env:
      SUBQL_ACCESS_TOKEN: ${{ secrets.SUBQL_ACCESS_TOKEN }}
      ENDPOINT: ${{ secrets.ENDPOINT }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install Bun
        run: |
          export BUN_INSTALL="$HOME/.bun"
          curl -fsSL https://bun.sh/install | bash
          echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $GITHUB_ENV
          source /root/.bashrc
      - run: bun
      - name: Codegen
        run: bun codegen
      - name: Version
        run: npx subql --version
      - name: repo
        run: echo ${{github.repository}}
      - name: Publish and Deploy
        run: |
          sh .github/workflows/scripts/publish-deploy.sh -o ${{github.repository}} -p ${{github.event.inputs.projectName}} -e ${{secrets.ENDPOINT}}
