name: PR
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Verify Bun installation
        run: bun --version
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Navigating to the indexer directory
        run: cd apps/indexer
      - name: Codegen
        run: bun codegen
        timeout-minutes: 5
      - name: Build
        run: bun run build
        timeout-minutes: 10
      - name: Install test dependencies
        run: bun add --dev @subql/node-stellar
      - name: Run tests with Subquery Node
        run: bunx subql-node-stellar test -f ${{ github.workspace }}
        timeout-minutes: 15
