name: PR
on:
  pull_request:
    paths-ignore:
      - ".github/workflows/**"
jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install Bun
        run: |
          export BUN_INSTALL="$HOME/.bun"
          curl -fsSL https://bun.sh/install | bash
          export PATH="$BUN_INSTALL/bin:$PATH"
      - run: bun
      - name: Codegen
        run: bun codegen
      - name: Build
        run: bun run build
      - name: Install subql-node-stellar
        run: bun add -g @subql/node-stellar
      - name: Run tests with Subquery Node
        run: subql-node-stellar test -f ${{ github.workspace }}
